// Auto-generated from Kanpur CSV datasets. Do not edit directly.
export const INITIAL_HOSPITALS = [
  {
    "hospital_id": "H001",
    "name": "LLR Hospital (Hallet)",
    "hospital_type": "Government",
    "address": "Darshan Purwa, Sarvodaya Nagar, Kanpur, UP 208002",
    "latitude": 26.4674,
    "longitude": 80.3208,
    "total_capacity": 100,
    "current_occupancy": 35,
    "icu_capacity": 5,
    "icu_occupancy": 2,
    "emergency_available": true,
    "teleconsultation_available": false
  },
  {
    "hospital_id": "H002",
    "name": "UHM Govt Hospital Kanpur",
    "hospital_type": "Government",
    "address": "39/24, Meston Road, Parade, Kanpur, UP 208001",
    "latitude": 26.459,
    "longitude": 80.343,
    "total_capacity": 150,
    "current_occupancy": 46,
    "icu_capacity": 10,
    "icu_occupancy": 5,
    "emergency_available": true,
    "teleconsultation_available": true
  },
  {
    "hospital_id": "H003",
    "name": "KPM Hospital",
    "hospital_type": "Government",
    "address": "Birhana Road, Naughara, Kanpur, UP",
    "latitude": 26.4598,
    "longitude": 80.3465,
    "total_capacity": 200,
    "current_occupancy": 57,
    "icu_capacity": 15,
    "icu_occupancy": 8,
    "emergency_available": true,
    "teleconsultation_available": true
  },
  {
    "hospital_id": "H004",
    "name": "Regency Multi Super Speciality Hospital",
    "hospital_type": "Private",
    "address": "Sarvodaya Nagar, Kanpur, UP",
    "latitude": 26.477,
    "longitude": 80.313,
    "total_capacity": 250,
    "current_occupancy": 68,
    "icu_capacity": 20,
    "icu_occupancy": 11,
    "emergency_available": true,
    "teleconsultation_available": false
  },
  {
    "hospital_id": "H005",
    "name": "Apollo Spectra Hospitals - Kanpur",
    "hospital_type": "Private",
    "address": "14/138, Mall Road, Chunniganj, Kanpur, UP 208001",
    "latitude": 26.4695,
    "longitude": 80.3455,
    "total_capacity": 300,
    "current_occupancy": 79,
    "icu_capacity": 25,
    "icu_occupancy": 2,
    "emergency_available": true,
    "teleconsultation_available": true
  },
  {
    "hospital_id": "H006",
    "name": "Krishna Super Speciality Hospital",
    "hospital_type": "Private",
    "address": "363, near Tatmil Chauraha, Harris Ganj, Kanpur, UP 208004",
    "latitude": 26.4475,
    "longitude": 80.3425,
    "total_capacity": 350,
    "current_occupancy": 35,
    "icu_capacity": 5,
    "icu_occupancy": 5,
    "emergency_available": true,
    "teleconsultation_available": true
  },
  {
    "hospital_id": "H007",
    "name": "Ujala Cygnus Noble Hospital Kanpur",
    "hospital_type": "Private",
    "address": "113/16 A, Khalasi Line, Swaroop Nagar, Kanpur, UP 208002",
    "latitude": 26.481,
    "longitude": 80.319,
    "total_capacity": 100,
    "current_occupancy": 46,
    "icu_capacity": 10,
    "icu_occupancy": 8,
    "emergency_available": true,
    "teleconsultation_available": false
  },
  {
    "hospital_id": "H008",
    "name": "Ujala Cygnus Kulwanti Hospital",
    "hospital_type": "Private",
    "address": "117/N/8, Kakadeo, Kanpur, UP 208025",
    "latitude": 26.487,
    "longitude": 80.305,
    "total_capacity": 150,
    "current_occupancy": 57,
    "icu_capacity": 15,
    "icu_occupancy": 11,
    "emergency_available": true,
    "teleconsultation_available": true
  },
  {
    "hospital_id": "H009",
    "name": "Kanishk Super Speciality Hospital",
    "hospital_type": "Private",
    "address": "10/503-A, Khalasi Line, Kanpur, UP 208002",
    "latitude": 26.4805,
    "longitude": 80.317,
    "total_capacity": 200,
    "current_occupancy": 68,
    "icu_capacity": 20,
    "icu_occupancy": 2,
    "emergency_available": true,
    "teleconsultation_available": true
  },
  {
    "hospital_id": "H010",
    "name": "Lotus Super Specialty Hospital",
    "hospital_type": "Private",
    "address": "120/500(22), Lajpat Nagar, Kanpur, UP 208005",
    "latitude": 26.465,
    "longitude": 80.311,
    "total_capacity": 250,
    "current_occupancy": 79,
    "icu_capacity": 25,
    "icu_occupancy": 5,
    "emergency_available": true,
    "teleconsultation_available": false
  },
  {
    "hospital_id": "H011",
    "name": "Kanpur Medical Centre",
    "hospital_type": "Private",
    "address": "120/500(24), Govind Nagar Road, Lajpat Nagar, Kanpur, UP 208005",
    "latitude": 26.465,
    "longitude": 80.3095,
    "total_capacity": 300,
    "current_occupancy": 35,
    "icu_capacity": 5,
    "icu_occupancy": 8,
    "emergency_available": true,
    "teleconsultation_available": true
  },
  {
    "hospital_id": "H012",
    "name": "Neuron Super Speciality Hospital",
    "hospital_type": "Private",
    "address": "L/450, Double Pulia, Kakadeo, Kanpur, UP 208025",
    "latitude": 26.49,
    "longitude": 80.3,
    "total_capacity": 350,
    "current_occupancy": 46,
    "icu_capacity": 10,
    "icu_occupancy": 11,
    "emergency_available": true,
    "teleconsultation_available": true
  },
  {
    "hospital_id": "H013",
    "name": "Lifetron Hospital",
    "hospital_type": "Private",
    "address": "Keshav Puram, Kalyanpur, Kanpur, UP 208019",
    "latitude": 26.512,
    "longitude": 80.27,
    "total_capacity": 100,
    "current_occupancy": 57,
    "icu_capacity": 15,
    "icu_occupancy": 2,
    "emergency_available": true,
    "teleconsultation_available": false
  },
  {
    "hospital_id": "H014",
    "name": "Dhanvantri Superspeciality Hospital",
    "hospital_type": "Private",
    "address": "Vasant Vihar, Naubasta, Kanpur, UP 208021",
    "latitude": 26.414,
    "longitude": 80.331,
    "total_capacity": 150,
    "current_occupancy": 68,
    "icu_capacity": 20,
    "icu_occupancy": 5,
    "emergency_available": true,
    "teleconsultation_available": true
  },
  {
    "hospital_id": "H015",
    "name": "Mahadeva Multi Speciality Hospital",
    "hospital_type": "Private",
    "address": "Vasant Vihar, Naubasta, Kanpur, UP 208021",
    "latitude": 26.4145,
    "longitude": 80.332,
    "total_capacity": 200,
    "current_occupancy": 79,
    "icu_capacity": 25,
    "icu_occupancy": 8,
    "emergency_available": true,
    "teleconsultation_available": true
  },
  {
    "hospital_id": "H016",
    "name": "Family Hospital & Research Centre",
    "hospital_type": "Private",
    "address": "Hanspuram, Naubasta, Kanpur, UP 208021",
    "latitude": 26.41,
    "longitude": 80.33,
    "total_capacity": 250,
    "current_occupancy": 35,
    "icu_capacity": 5,
    "icu_occupancy": 11,
    "emergency_available": true,
    "teleconsultation_available": false
  },
  {
    "hospital_id": "H017",
    "name": "Paramount Hospital",
    "hospital_type": "Private",
    "address": "Awas Vikas Road, Hanspuram, Naubasta, Kanpur, UP 208021",
    "latitude": 26.409,
    "longitude": 80.326,
    "total_capacity": 300,
    "current_occupancy": 46,
    "icu_capacity": 10,
    "icu_occupancy": 2,
    "emergency_available": true,
    "teleconsultation_available": true
  },
  {
    "hospital_id": "H018",
    "name": "Utkarsh Hospital",
    "hospital_type": "Private",
    "address": "Baba Nagar, Naubasta, Kanpur, UP 208021",
    "latitude": 26.416,
    "longitude": 80.338,
    "total_capacity": 350,
    "current_occupancy": 57,
    "icu_capacity": 15,
    "icu_occupancy": 5,
    "emergency_available": true,
    "teleconsultation_available": true
  },
  {
    "hospital_id": "H019",
    "name": "K.P.S. Hospital",
    "hospital_type": "Private",
    "address": "PAC Bypass, New Azad Nagar, Kanpur, UP 208011",
    "latitude": 26.43,
    "longitude": 80.255,
    "total_capacity": 100,
    "current_occupancy": 68,
    "icu_capacity": 20,
    "icu_occupancy": 8,
    "emergency_available": true,
    "teleconsultation_available": false
  },
  {
    "hospital_id": "H020",
    "name": "Panacea Multi Super Specialty Hospital",
    "hospital_type": "Private",
    "address": "117/473 L Block, Kakadeo, Kanpur, UP 208005",
    "latitude": 26.488,
    "longitude": 80.302,
    "total_capacity": 150,
    "current_occupancy": 79,
    "icu_capacity": 25,
    "icu_occupancy": 11,
    "emergency_available": true,
    "teleconsultation_available": true
  }
];
export const INITIAL_DOCTORS = [
  {
    "doctor_id": "D001",
    "name": "Dr. A.C. Agarwal",
    "qualification": "MBBS, MD (Medicine)",
    "specialty": "General Medicine",
    "clinic_or_affiliation": "CGHS, Civil Lines",
    "hospital_id": "H001",
    "experience_years": 5,
    "consultation_duration": 15,
    "available_now": false,
    "queue_count": 0,
    "max_daily_patients": 18,
    "workload": 25.0,
    "emergency_available": false,
    "teleconsultation_available": false,
    "rating": 3.8
  },
  {
    "doctor_id": "D002",
    "name": "Dr. Rita Mittal",
    "qualification": "MBBS, MS (Obst. & Gyne.)",
    "specialty": "Obstetrics & Gynaecology",
    "clinic_or_affiliation": "58/86, Birhana Road, Kanpur",
    "hospital_id": "H002",
    "experience_years": 8,
    "consultation_duration": 20,
    "available_now": true,
    "queue_count": 3,
    "max_daily_patients": 24,
    "workload": 32.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 3.8
  },
  {
    "doctor_id": "D003",
    "name": "Dr. A.K. Agarwal",
    "qualification": "MBBS, MD (TB & Chest)",
    "specialty": "Pulmonology",
    "clinic_or_affiliation": "104A/228, P. Road, Kanpur",
    "hospital_id": "H003",
    "experience_years": 11,
    "consultation_duration": 25,
    "available_now": true,
    "queue_count": 6,
    "max_daily_patients": 30,
    "workload": 39.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 3.9
  },
  {
    "doctor_id": "D004",
    "name": "Dr. Lata Agarwal",
    "qualification": "MBBS, DGO (Obst. & Gyne.)",
    "specialty": "Obstetrics & Gynaecology",
    "clinic_or_affiliation": "104A/228, P. Road, Kanpur",
    "hospital_id": "H004",
    "experience_years": 14,
    "consultation_duration": 30,
    "available_now": true,
    "queue_count": 0,
    "max_daily_patients": 36,
    "workload": 46.0,
    "emergency_available": false,
    "teleconsultation_available": true,
    "rating": 3.9
  },
  {
    "doctor_id": "D005",
    "name": "Dr. Ajay Kumar Agarwal",
    "qualification": "MBBS, MS (ENT)",
    "specialty": "ENT",
    "clinic_or_affiliation": "E.N.T. Care Clinic, Ramadevi, Kanpur",
    "hospital_id": "H002",
    "experience_years": 17,
    "consultation_duration": 15,
    "available_now": true,
    "queue_count": 3,
    "max_daily_patients": 42,
    "workload": 53.0,
    "emergency_available": true,
    "teleconsultation_available": false,
    "rating": 4.0
  },
  {
    "doctor_id": "D006",
    "name": "Dr. Akhilesh Agarwal",
    "qualification": "MBBS, MD (Forensic Medicine)",
    "specialty": "Forensic Medicine",
    "clinic_or_affiliation": "MRA Govt. Medical College, UP",
    "hospital_id": "H006",
    "experience_years": 20,
    "consultation_duration": 20,
    "available_now": false,
    "queue_count": 6,
    "max_daily_patients": 18,
    "workload": 60.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.0
  },
  {
    "doctor_id": "D007",
    "name": "Dr. Kajali Gupta",
    "qualification": "MBBS, DGO",
    "specialty": "Obstetrics & Gynaecology",
    "clinic_or_affiliation": "AHM & Dufferin Hospital, Kanpur",
    "hospital_id": "H002",
    "experience_years": 23,
    "consultation_duration": 25,
    "available_now": true,
    "queue_count": 0,
    "max_daily_patients": 24,
    "workload": 67.0,
    "emergency_available": false,
    "teleconsultation_available": true,
    "rating": 4.1
  },
  {
    "doctor_id": "D008",
    "name": "Dr. Amitabh Agarwal",
    "qualification": "MBBS, MD",
    "specialty": "General Medicine",
    "clinic_or_affiliation": "Kanpur",
    "hospital_id": "H008",
    "experience_years": 26,
    "consultation_duration": 30,
    "available_now": false,
    "queue_count": 3,
    "max_daily_patients": 30,
    "workload": 74.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.1
  },
  {
    "doctor_id": "D009",
    "name": "Dr. Love Leena Agarwal",
    "qualification": "MBBS, MD",
    "specialty": "General Medicine",
    "clinic_or_affiliation": "Kanpur",
    "hospital_id": "H009",
    "experience_years": 29,
    "consultation_duration": 15,
    "available_now": true,
    "queue_count": 6,
    "max_daily_patients": 36,
    "workload": 81.0,
    "emergency_available": true,
    "teleconsultation_available": false,
    "rating": 4.2
  },
  {
    "doctor_id": "D010",
    "name": "Dr. Ankit Agarwal",
    "qualification": "MBBS, MD (Skin & VD)",
    "specialty": "Dermatology",
    "clinic_or_affiliation": "Dr. Agarwal Skin & Laser Centre, Swaroop Nagar",
    "hospital_id": "H010",
    "experience_years": 6,
    "consultation_duration": 20,
    "available_now": true,
    "queue_count": 0,
    "max_daily_patients": 42,
    "workload": 88.0,
    "emergency_available": false,
    "teleconsultation_available": true,
    "rating": 4.2
  },
  {
    "doctor_id": "D011",
    "name": "Dr. Ruchika Agarwal",
    "qualification": "MBBS, MS (Ophthalmics)",
    "specialty": "Ophthalmology",
    "clinic_or_affiliation": "Rama Medical College, Kanpur",
    "hospital_id": "H011",
    "experience_years": 9,
    "consultation_duration": 25,
    "available_now": true,
    "queue_count": 3,
    "max_daily_patients": 18,
    "workload": 25.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.3
  },
  {
    "doctor_id": "D012",
    "name": "Dr. Ankit Agarwal",
    "qualification": "MBBS, MD (Medicine)",
    "specialty": "General Medicine",
    "clinic_or_affiliation": "Ordinance Hospital, Armapur",
    "hospital_id": "H012",
    "experience_years": 12,
    "consultation_duration": 30,
    "available_now": true,
    "queue_count": 6,
    "max_daily_patients": 24,
    "workload": 32.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.3
  },
  {
    "doctor_id": "D013",
    "name": "Dr. Anuj Agarwal",
    "qualification": "MBBS",
    "specialty": "General Medicine",
    "clinic_or_affiliation": "Kanpur",
    "hospital_id": "H013",
    "experience_years": 15,
    "consultation_duration": 15,
    "available_now": false,
    "queue_count": 0,
    "max_daily_patients": 30,
    "workload": 39.0,
    "emergency_available": false,
    "teleconsultation_available": false,
    "rating": 3.8
  },
  {
    "doctor_id": "D014",
    "name": "Dr. Rekha Agarwal",
    "qualification": "MD (Anaesthesia)",
    "specialty": "Anaesthesiology",
    "clinic_or_affiliation": "Kanpur",
    "hospital_id": "H014",
    "experience_years": 18,
    "consultation_duration": 20,
    "available_now": true,
    "queue_count": 3,
    "max_daily_patients": 36,
    "workload": 46.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 3.8
  },
  {
    "doctor_id": "D015",
    "name": "Dr. Apurva Agarwal",
    "qualification": "MBBS, MD (Anesthesia)",
    "specialty": "Anaesthesiology",
    "clinic_or_affiliation": "Dept. of Anesthesia GSVM Medical College",
    "hospital_id": "H001",
    "experience_years": 21,
    "consultation_duration": 25,
    "available_now": false,
    "queue_count": 6,
    "max_daily_patients": 42,
    "workload": 53.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 3.9
  },
  {
    "doctor_id": "D016",
    "name": "Dr. Shaily Agarwal",
    "qualification": "MBBS, MS (Obst. & Gyne.)",
    "specialty": "Obstetrics & Gynaecology",
    "clinic_or_affiliation": "235/11, Shastri Nagar, Kanpur",
    "hospital_id": "H016",
    "experience_years": 24,
    "consultation_duration": 30,
    "available_now": true,
    "queue_count": 0,
    "max_daily_patients": 18,
    "workload": 60.0,
    "emergency_available": false,
    "teleconsultation_available": true,
    "rating": 3.9
  },
  {
    "doctor_id": "D017",
    "name": "Dr. Devendra Agarwal",
    "qualification": "MBBS, MS, M.Ch (Paediatric Surgery)",
    "specialty": "Paediatric Surgery",
    "clinic_or_affiliation": "Kanpur",
    "hospital_id": "H008",
    "experience_years": 27,
    "consultation_duration": 15,
    "available_now": true,
    "queue_count": 3,
    "max_daily_patients": 24,
    "workload": 67.0,
    "emergency_available": true,
    "teleconsultation_available": false,
    "rating": 4.0
  },
  {
    "doctor_id": "D018",
    "name": "Dr. Dilip Agarwal",
    "qualification": "MBBS, D. Orth.",
    "specialty": "Orthopaedics",
    "clinic_or_affiliation": "Kanpur",
    "hospital_id": "H018",
    "experience_years": 30,
    "consultation_duration": 20,
    "available_now": true,
    "queue_count": 6,
    "max_daily_patients": 30,
    "workload": 74.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.0
  },
  {
    "doctor_id": "D019",
    "name": "Dr. Kiran Agarwal",
    "qualification": "MBBS, DGO (Obst. & Gyne.)",
    "specialty": "Obstetrics & Gynaecology",
    "clinic_or_affiliation": "Kanpur",
    "hospital_id": "H019",
    "experience_years": 7,
    "consultation_duration": 25,
    "available_now": true,
    "queue_count": 0,
    "max_daily_patients": 36,
    "workload": 81.0,
    "emergency_available": false,
    "teleconsultation_available": true,
    "rating": 4.1
  },
  {
    "doctor_id": "D020",
    "name": "Dr. Gaurav Agarwal",
    "qualification": "MBBS, DTCD",
    "specialty": "Pulmonology",
    "clinic_or_affiliation": "District Hospital, Unnao",
    "hospital_id": "H020",
    "experience_years": 10,
    "consultation_duration": 30,
    "available_now": false,
    "queue_count": 3,
    "max_daily_patients": 42,
    "workload": 88.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.1
  },
  {
    "doctor_id": "D021",
    "name": "Dr. Gaurav Agarwal",
    "qualification": "MBBS, MS (Ophthalmology)",
    "specialty": "Ophthalmology",
    "clinic_or_affiliation": "Keshavpuram, Kanpur",
    "hospital_id": "H001",
    "experience_years": 13,
    "consultation_duration": 15,
    "available_now": true,
    "queue_count": 6,
    "max_daily_patients": 18,
    "workload": 25.0,
    "emergency_available": true,
    "teleconsultation_available": false,
    "rating": 4.2
  },
  {
    "doctor_id": "D022",
    "name": "Dr. Harsh Kumar Agarwal",
    "qualification": "MBBS, MD, DM (Cardiology)",
    "specialty": "Cardiology",
    "clinic_or_affiliation": "Regency Hospital, Sarvodaya Nagar",
    "hospital_id": "H004",
    "experience_years": 16,
    "consultation_duration": 20,
    "available_now": false,
    "queue_count": 0,
    "max_daily_patients": 24,
    "workload": 32.0,
    "emergency_available": false,
    "teleconsultation_available": true,
    "rating": 4.2
  },
  {
    "doctor_id": "D023",
    "name": "Dr. Hemant Agarwal",
    "qualification": "MBBS, DNB Med",
    "specialty": "General Medicine",
    "clinic_or_affiliation": "CGHS WC, Ratanlal Nagar",
    "hospital_id": "H003",
    "experience_years": 19,
    "consultation_duration": 25,
    "available_now": true,
    "queue_count": 3,
    "max_daily_patients": 30,
    "workload": 39.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.3
  },
  {
    "doctor_id": "D024",
    "name": "Dr. Himanshu Agarwal",
    "qualification": "MBBS",
    "specialty": "General Medicine",
    "clinic_or_affiliation": "Kanpur",
    "hospital_id": "H004",
    "experience_years": 22,
    "consultation_duration": 30,
    "available_now": true,
    "queue_count": 6,
    "max_daily_patients": 36,
    "workload": 46.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.3
  },
  {
    "doctor_id": "D025",
    "name": "Dr. Jaya Agarwal",
    "qualification": "MBBS, MD (Paediatrics)",
    "specialty": "Paediatrics",
    "clinic_or_affiliation": "Kanpur",
    "hospital_id": "H005",
    "experience_years": 25,
    "consultation_duration": 15,
    "available_now": true,
    "queue_count": 0,
    "max_daily_patients": 42,
    "workload": 53.0,
    "emergency_available": false,
    "teleconsultation_available": false,
    "rating": 3.8
  },
  {
    "doctor_id": "D026",
    "name": "Dr. Jitendra Agarwal",
    "qualification": "MBBS, MS (Surgery)",
    "specialty": "General Surgery",
    "clinic_or_affiliation": "Kanpur",
    "hospital_id": "H006",
    "experience_years": 28,
    "consultation_duration": 20,
    "available_now": true,
    "queue_count": 3,
    "max_daily_patients": 18,
    "workload": 60.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 3.8
  },
  {
    "doctor_id": "D027",
    "name": "Dr. Krishna Chandra Agarwal",
    "qualification": "MBBS, MD (Paediatrics)",
    "specialty": "Paediatrics",
    "clinic_or_affiliation": "48/254, Generalganj, Kanpur",
    "hospital_id": "H007",
    "experience_years": 5,
    "consultation_duration": 25,
    "available_now": false,
    "queue_count": 6,
    "max_daily_patients": 24,
    "workload": 67.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 3.9
  },
  {
    "doctor_id": "D028",
    "name": "Dr. K.K. Agarwal",
    "qualification": "MBBS, MD (Medicine)",
    "specialty": "General Medicine",
    "clinic_or_affiliation": "Civil Lines, Kanpur",
    "hospital_id": "H008",
    "experience_years": 8,
    "consultation_duration": 30,
    "available_now": true,
    "queue_count": 0,
    "max_daily_patients": 30,
    "workload": 74.0,
    "emergency_available": false,
    "teleconsultation_available": true,
    "rating": 3.9
  },
  {
    "doctor_id": "D029",
    "name": "Dr. Asha Agarwal",
    "qualification": "MD (Pathology)",
    "specialty": "Pathology",
    "clinic_or_affiliation": "Pathway Diagnostics, Lajpat Nagar",
    "hospital_id": "H009",
    "experience_years": 11,
    "consultation_duration": 15,
    "available_now": false,
    "queue_count": 3,
    "max_daily_patients": 36,
    "workload": 81.0,
    "emergency_available": true,
    "teleconsultation_available": false,
    "rating": 4.0
  },
  {
    "doctor_id": "D030",
    "name": "Dr. Kartik Agarwal",
    "qualification": "MBBS, MD (Medicine)",
    "specialty": "General Medicine",
    "clinic_or_affiliation": "Civil Lines, Kanpur",
    "hospital_id": "H010",
    "experience_years": 14,
    "consultation_duration": 20,
    "available_now": true,
    "queue_count": 6,
    "max_daily_patients": 42,
    "workload": 88.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.0
  },
  {
    "doctor_id": "D031",
    "name": "Dr. M.P. Agarwal",
    "qualification": "MBBS, DCP (Pathology)",
    "specialty": "Pathology",
    "clinic_or_affiliation": "Kanpur",
    "hospital_id": "H011",
    "experience_years": 17,
    "consultation_duration": 25,
    "available_now": true,
    "queue_count": 0,
    "max_daily_patients": 18,
    "workload": 25.0,
    "emergency_available": false,
    "teleconsultation_available": true,
    "rating": 4.1
  },
  {
    "doctor_id": "D032",
    "name": "Dr. Manisha Agarwal",
    "qualification": "MBBS (Trained in Ultrasound)",
    "specialty": "Radiology/Imaging",
    "clinic_or_affiliation": "Lal Bangla, Kanpur",
    "hospital_id": "H012",
    "experience_years": 20,
    "consultation_duration": 30,
    "available_now": true,
    "queue_count": 3,
    "max_daily_patients": 24,
    "workload": 32.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.1
  },
  {
    "doctor_id": "D033",
    "name": "Dr. Manoj Agarwal",
    "qualification": "MBBS, MD (Medicine)",
    "specialty": "General Medicine",
    "clinic_or_affiliation": "Kanpur",
    "hospital_id": "H013",
    "experience_years": 23,
    "consultation_duration": 15,
    "available_now": true,
    "queue_count": 6,
    "max_daily_patients": 30,
    "workload": 39.0,
    "emergency_available": true,
    "teleconsultation_available": false,
    "rating": 4.2
  },
  {
    "doctor_id": "D034",
    "name": "Dr. M.K. Agarwal",
    "qualification": "MBBS",
    "specialty": "General Medicine",
    "clinic_or_affiliation": "Kalyanpur, Kanpur",
    "hospital_id": "H014",
    "experience_years": 26,
    "consultation_duration": 20,
    "available_now": false,
    "queue_count": 0,
    "max_daily_patients": 36,
    "workload": 46.0,
    "emergency_available": false,
    "teleconsultation_available": true,
    "rating": 4.2
  },
  {
    "doctor_id": "D035",
    "name": "Dr. Mayuri Agarwal",
    "qualification": "MBBS, MD (Medicine)",
    "specialty": "General Medicine",
    "clinic_or_affiliation": "Kanpur",
    "hospital_id": "H015",
    "experience_years": 29,
    "consultation_duration": 25,
    "available_now": true,
    "queue_count": 3,
    "max_daily_patients": 42,
    "workload": 53.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.3
  },
  {
    "doctor_id": "D036",
    "name": "Dr. Neha Agarwal",
    "qualification": "MBBS, MD (Paediatrics)",
    "specialty": "Paediatrics",
    "clinic_or_affiliation": "CGHS, Kanpur",
    "hospital_id": "H016",
    "experience_years": 6,
    "consultation_duration": 30,
    "available_now": false,
    "queue_count": 6,
    "max_daily_patients": 18,
    "workload": 60.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.3
  },
  {
    "doctor_id": "D037",
    "name": "Dr. Pawan Agarwal",
    "qualification": "MBBS, DA (Anaesthesia)",
    "specialty": "Anaesthesiology",
    "clinic_or_affiliation": "CHC, Chaubeypur, Kanpur",
    "hospital_id": "H017",
    "experience_years": 9,
    "consultation_duration": 15,
    "available_now": true,
    "queue_count": 0,
    "max_daily_patients": 24,
    "workload": 67.0,
    "emergency_available": false,
    "teleconsultation_available": false,
    "rating": 3.8
  },
  {
    "doctor_id": "D038",
    "name": "Dr. Pradeep Agarwal",
    "qualification": "MBBS",
    "specialty": "General Medicine",
    "clinic_or_affiliation": "Barra-2, Kanpur",
    "hospital_id": "H018",
    "experience_years": 12,
    "consultation_duration": 20,
    "available_now": true,
    "queue_count": 3,
    "max_daily_patients": 30,
    "workload": 74.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 3.8
  },
  {
    "doctor_id": "D039",
    "name": "Dr. Pratibha Agarwal",
    "qualification": "MBBS",
    "specialty": "General Medicine",
    "clinic_or_affiliation": "Barra-2, Kanpur",
    "hospital_id": "H019",
    "experience_years": 15,
    "consultation_duration": 25,
    "available_now": true,
    "queue_count": 6,
    "max_daily_patients": 36,
    "workload": 81.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 3.9
  },
  {
    "doctor_id": "D040",
    "name": "Dr. Pradumn Agarwal",
    "qualification": "MBBS, MS (Ophthalmics)",
    "specialty": "Ophthalmology",
    "clinic_or_affiliation": "Kidwai Nagar, Kanpur",
    "hospital_id": "H020",
    "experience_years": 18,
    "consultation_duration": 30,
    "available_now": true,
    "queue_count": 0,
    "max_daily_patients": 42,
    "workload": 88.0,
    "emergency_available": false,
    "teleconsultation_available": true,
    "rating": 3.9
  },
  {
    "doctor_id": "D041",
    "name": "Dr. Punit Agarwal",
    "qualification": "MBBS, MD, DM, FCCN (Neurology)",
    "specialty": "Neurology",
    "clinic_or_affiliation": "Kanpur",
    "hospital_id": "H001",
    "experience_years": 21,
    "consultation_duration": 15,
    "available_now": false,
    "queue_count": 3,
    "max_daily_patients": 18,
    "workload": 25.0,
    "emergency_available": true,
    "teleconsultation_available": false,
    "rating": 4.0
  },
  {
    "doctor_id": "D042",
    "name": "Dr. Rahul Agarwal",
    "qualification": "MBBS, DNB (Ortho)",
    "specialty": "Orthopaedics",
    "clinic_or_affiliation": "Baradevi Chauraha, Kanpur",
    "hospital_id": "H002",
    "experience_years": 24,
    "consultation_duration": 20,
    "available_now": true,
    "queue_count": 6,
    "max_daily_patients": 24,
    "workload": 32.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.0
  },
  {
    "doctor_id": "D043",
    "name": "Dr. Neha Agarwal",
    "qualification": "MBBS, MS (Obst. & Gyne.)",
    "specialty": "Obstetrics & Gynaecology",
    "clinic_or_affiliation": "Baradevi Chauraha, Kanpur",
    "hospital_id": "H003",
    "experience_years": 27,
    "consultation_duration": 25,
    "available_now": false,
    "queue_count": 0,
    "max_daily_patients": 30,
    "workload": 39.0,
    "emergency_available": false,
    "teleconsultation_available": true,
    "rating": 4.1
  },
  {
    "doctor_id": "D044",
    "name": "Dr. Rajesh Agarwal",
    "qualification": "MBBS",
    "specialty": "General Medicine",
    "clinic_or_affiliation": "Regency Hospital, Kanpur",
    "hospital_id": "H004",
    "experience_years": 30,
    "consultation_duration": 30,
    "available_now": true,
    "queue_count": 3,
    "max_daily_patients": 36,
    "workload": 46.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.1
  },
  {
    "doctor_id": "D045",
    "name": "Dr. Rajesh Kumar Agarwal",
    "qualification": "MBBS, MS FIOS (Oncosurgery)",
    "specialty": "Surgical Oncology",
    "clinic_or_affiliation": "Ratan Cancer Hospital & Institute",
    "hospital_id": "H007",
    "experience_years": 7,
    "consultation_duration": 15,
    "available_now": true,
    "queue_count": 6,
    "max_daily_patients": 42,
    "workload": 53.0,
    "emergency_available": true,
    "teleconsultation_available": false,
    "rating": 4.2
  },
  {
    "doctor_id": "D046",
    "name": "Dr. Richa Agarwal",
    "qualification": "MBBS, MD, MNCCPI (TB & Chest)",
    "specialty": "Pulmonology",
    "clinic_or_affiliation": "Dr. O.P. Mittal Memorial Chest Clinic",
    "hospital_id": "H006",
    "experience_years": 10,
    "consultation_duration": 20,
    "available_now": true,
    "queue_count": 0,
    "max_daily_patients": 18,
    "workload": 60.0,
    "emergency_available": false,
    "teleconsultation_available": true,
    "rating": 4.2
  },
  {
    "doctor_id": "D047",
    "name": "Dr. Rajiv Agarwal",
    "qualification": "MBBS, MS (Orthopaedics)",
    "specialty": "Orthopaedics",
    "clinic_or_affiliation": "Model Town, Kanpur",
    "hospital_id": "H007",
    "experience_years": 13,
    "consultation_duration": 25,
    "available_now": true,
    "queue_count": 3,
    "max_daily_patients": 24,
    "workload": 67.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.3
  },
  {
    "doctor_id": "D048",
    "name": "Dr. Rajni Agarwal",
    "qualification": "MBBS, DM (Obst. & Gyne.)",
    "specialty": "Obstetrics & Gynaecology",
    "clinic_or_affiliation": "Kanpur",
    "hospital_id": "H008",
    "experience_years": 16,
    "consultation_duration": 30,
    "available_now": false,
    "queue_count": 6,
    "max_daily_patients": 30,
    "workload": 74.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.3
  },
  {
    "doctor_id": "D049",
    "name": "Dr. Rakesh Kumar Agarwal",
    "qualification": "MBBS, DMRD",
    "specialty": "Radiology",
    "clinic_or_affiliation": "Kanpur",
    "hospital_id": "H009",
    "experience_years": 19,
    "consultation_duration": 15,
    "available_now": true,
    "queue_count": 0,
    "max_daily_patients": 36,
    "workload": 81.0,
    "emergency_available": false,
    "teleconsultation_available": false,
    "rating": 3.8
  },
  {
    "doctor_id": "D050",
    "name": "Dr. S.C. Agarwal",
    "qualification": "MBBS, DVD (Skin & VD)",
    "specialty": "Dermatology",
    "clinic_or_affiliation": "Swaroop Nagar, Kanpur",
    "hospital_id": "H010",
    "experience_years": 22,
    "consultation_duration": 20,
    "available_now": false,
    "queue_count": 3,
    "max_daily_patients": 42,
    "workload": 88.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 3.8
  },
  {
    "doctor_id": "D051",
    "name": "Dr. Sameer Agarwal",
    "qualification": "MBBS, MD (Medicine)",
    "specialty": "General Medicine",
    "clinic_or_affiliation": "Deo Nagar, Kanpur",
    "hospital_id": "H011",
    "experience_years": 25,
    "consultation_duration": 25,
    "available_now": true,
    "queue_count": 6,
    "max_daily_patients": 18,
    "workload": 25.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 3.9
  },
  {
    "doctor_id": "D052",
    "name": "Dr. Surekha Agarwal",
    "qualification": "MBBS, MD (Paediatrics)",
    "specialty": "Paediatrics",
    "clinic_or_affiliation": "Jajmau, Kanpur",
    "hospital_id": "H012",
    "experience_years": 28,
    "consultation_duration": 30,
    "available_now": true,
    "queue_count": 0,
    "max_daily_patients": 24,
    "workload": 32.0,
    "emergency_available": false,
    "teleconsultation_available": true,
    "rating": 3.9
  },
  {
    "doctor_id": "D053",
    "name": "Dr. Sanjay Agarwal",
    "qualification": "MBBS, MS (ENT)",
    "specialty": "ENT",
    "clinic_or_affiliation": "Baradevi Chauraha, Kanpur",
    "hospital_id": "H013",
    "experience_years": 5,
    "consultation_duration": 15,
    "available_now": true,
    "queue_count": 3,
    "max_daily_patients": 30,
    "workload": 39.0,
    "emergency_available": true,
    "teleconsultation_available": false,
    "rating": 4.0
  },
  {
    "doctor_id": "D054",
    "name": "Dr. Priya Agarwal",
    "qualification": "MBBS, DGO (Obst. & Gynae.)",
    "specialty": "Obstetrics & Gynaecology",
    "clinic_or_affiliation": "Kidwai Nagar, Kanpur",
    "hospital_id": "H014",
    "experience_years": 8,
    "consultation_duration": 20,
    "available_now": true,
    "queue_count": 6,
    "max_daily_patients": 36,
    "workload": 46.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.0
  },
  {
    "doctor_id": "D055",
    "name": "Dr. Saurabh Agarwal",
    "qualification": "MBBS, MD (Medicine)",
    "specialty": "General Medicine",
    "clinic_or_affiliation": "Dept. of Medicine, GSVM Medical College",
    "hospital_id": "H001",
    "experience_years": 11,
    "consultation_duration": 25,
    "available_now": false,
    "queue_count": 0,
    "max_daily_patients": 42,
    "workload": 53.0,
    "emergency_available": false,
    "teleconsultation_available": true,
    "rating": 4.1
  },
  {
    "doctor_id": "D056",
    "name": "Dr. Shubha Agarwal",
    "qualification": "MS (Obst. & Gynae.)",
    "specialty": "Obstetrics & Gynaecology",
    "clinic_or_affiliation": "Kanpur",
    "hospital_id": "H016",
    "experience_years": 14,
    "consultation_duration": 30,
    "available_now": true,
    "queue_count": 3,
    "max_daily_patients": 18,
    "workload": 60.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.1
  },
  {
    "doctor_id": "D057",
    "name": "Dr. Uma Agarwal",
    "qualification": "MBBS, MS (Ophthalmology)",
    "specialty": "Ophthalmology",
    "clinic_or_affiliation": "Ashok Nagar, Kanpur",
    "hospital_id": "H017",
    "experience_years": 17,
    "consultation_duration": 15,
    "available_now": false,
    "queue_count": 6,
    "max_daily_patients": 24,
    "workload": 67.0,
    "emergency_available": true,
    "teleconsultation_available": false,
    "rating": 4.2
  },
  {
    "doctor_id": "D058",
    "name": "Dr. Umesh Kumar Agarwal",
    "qualification": "MBBS, D. Orth",
    "specialty": "Orthopaedics",
    "clinic_or_affiliation": "ESI Hospital, Pandu Nagar",
    "hospital_id": "H018",
    "experience_years": 20,
    "consultation_duration": 20,
    "available_now": true,
    "queue_count": 0,
    "max_daily_patients": 30,
    "workload": 74.0,
    "emergency_available": false,
    "teleconsultation_available": true,
    "rating": 4.2
  },
  {
    "doctor_id": "D059",
    "name": "Dr. V.B. Agarwal",
    "qualification": "MBBS, MD (TB & Chest)",
    "specialty": "Pulmonology",
    "clinic_or_affiliation": "Kanpur",
    "hospital_id": "H019",
    "experience_years": 23,
    "consultation_duration": 25,
    "available_now": true,
    "queue_count": 3,
    "max_daily_patients": 36,
    "workload": 81.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.3
  },
  {
    "doctor_id": "D060",
    "name": "Dr. Pratibha Agarwal",
    "qualification": "MBBS, DGO (Obst. & Gyne.)",
    "specialty": "Obstetrics & Gynaecology",
    "clinic_or_affiliation": "Kanpur",
    "hospital_id": "H020",
    "experience_years": 26,
    "consultation_duration": 30,
    "available_now": true,
    "queue_count": 6,
    "max_daily_patients": 42,
    "workload": 88.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.3
  },
  {
    "doctor_id": "D061",
    "name": "Dr. Akshay Agnihotri",
    "qualification": "MBBS, MS (Orthopaedics)",
    "specialty": "Orthopaedics",
    "clinic_or_affiliation": "Kanpur",
    "hospital_id": "H001",
    "experience_years": 29,
    "consultation_duration": 15,
    "available_now": true,
    "queue_count": 0,
    "max_daily_patients": 18,
    "workload": 25.0,
    "emergency_available": false,
    "teleconsultation_available": false,
    "rating": 3.8
  },
  {
    "doctor_id": "D062",
    "name": "Dr. Mamta Agnihotri",
    "qualification": "MBBS, MS (Obst. & Gyne.)",
    "specialty": "Obstetrics & Gynaecology",
    "clinic_or_affiliation": "Kanpur",
    "hospital_id": "H002",
    "experience_years": 6,
    "consultation_duration": 20,
    "available_now": false,
    "queue_count": 3,
    "max_daily_patients": 24,
    "workload": 32.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 3.8
  },
  {
    "doctor_id": "D063",
    "name": "Dr. Neerja Agnihotri",
    "qualification": "MBBS, DGO (Obst. & Gyne.)",
    "specialty": "Obstetrics & Gynaecology",
    "clinic_or_affiliation": "Kanpur",
    "hospital_id": "H003",
    "experience_years": 9,
    "consultation_duration": 25,
    "available_now": true,
    "queue_count": 6,
    "max_daily_patients": 30,
    "workload": 39.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 3.9
  },
  {
    "doctor_id": "D064",
    "name": "Dr. Prem Kumar Agnihotri",
    "qualification": "MBBS",
    "specialty": "General Medicine",
    "clinic_or_affiliation": "Sewa Chandra Prabha Hospital, Barra",
    "hospital_id": "H004",
    "experience_years": 12,
    "consultation_duration": 30,
    "available_now": false,
    "queue_count": 0,
    "max_daily_patients": 36,
    "workload": 46.0,
    "emergency_available": false,
    "teleconsultation_available": true,
    "rating": 3.9
  },
  {
    "doctor_id": "D065",
    "name": "Dr. R.C. Agnihotri",
    "qualification": "MBBS, DCP (Pathology)",
    "specialty": "Pathology",
    "clinic_or_affiliation": "Universal Pathology Lab & Blood Bank",
    "hospital_id": "H005",
    "experience_years": 15,
    "consultation_duration": 15,
    "available_now": true,
    "queue_count": 3,
    "max_daily_patients": 42,
    "workload": 53.0,
    "emergency_available": true,
    "teleconsultation_available": false,
    "rating": 4.0
  },
  {
    "doctor_id": "D066",
    "name": "Dr. Meera Agnihotri",
    "qualification": "DGO, MS (Obst. & Gyne), MAMS, FICOG, FICS, FICMCH",
    "specialty": "Obstetrics & Gynaecology",
    "clinic_or_affiliation": "Jeevani Hospital, Swaroop Nagar",
    "hospital_id": "H007",
    "experience_years": 18,
    "consultation_duration": 20,
    "available_now": true,
    "queue_count": 6,
    "max_daily_patients": 18,
    "workload": 60.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.0
  },
  {
    "doctor_id": "D067",
    "name": "Dr. Srivar Agnihotri",
    "qualification": "MBBS, D. Orth. (Orthopedics)",
    "specialty": "Orthopaedics",
    "clinic_or_affiliation": "Kanpur",
    "hospital_id": "H007",
    "experience_years": 21,
    "consultation_duration": 25,
    "available_now": true,
    "queue_count": 0,
    "max_daily_patients": 24,
    "workload": 67.0,
    "emergency_available": false,
    "teleconsultation_available": true,
    "rating": 4.1
  },
  {
    "doctor_id": "D068",
    "name": "Dr. A.K. Agrahari",
    "qualification": "MBBS",
    "specialty": "General Medicine",
    "clinic_or_affiliation": "Dwarikadheesh Road, Kanpur",
    "hospital_id": "H008",
    "experience_years": 24,
    "consultation_duration": 30,
    "available_now": true,
    "queue_count": 3,
    "max_daily_patients": 30,
    "workload": 74.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.1
  },
  {
    "doctor_id": "D069",
    "name": "Dr. Amit Agrawal",
    "qualification": "MBBS, MS, DNB, M.Ch (Orthopaedics)",
    "specialty": "Orthopaedics",
    "clinic_or_affiliation": "Satya Trauma Maternity Centre",
    "hospital_id": "H009",
    "experience_years": 27,
    "consultation_duration": 15,
    "available_now": false,
    "queue_count": 6,
    "max_daily_patients": 36,
    "workload": 81.0,
    "emergency_available": true,
    "teleconsultation_available": false,
    "rating": 4.2
  },
  {
    "doctor_id": "D070",
    "name": "Dr. Manisha Agrawal",
    "qualification": "MBBS, MS, DNB, FICMCH (Obst. & Gynae.)",
    "specialty": "Obstetrics & Gynaecology",
    "clinic_or_affiliation": "Satya Trauma Maternity Centre",
    "hospital_id": "H010",
    "experience_years": 30,
    "consultation_duration": 20,
    "available_now": true,
    "queue_count": 0,
    "max_daily_patients": 42,
    "workload": 88.0,
    "emergency_available": false,
    "teleconsultation_available": true,
    "rating": 4.2
  },
  {
    "doctor_id": "D071",
    "name": "Dr. Anoop Agrawal",
    "qualification": "MBBS, MS (Orthopaedics)",
    "specialty": "Orthopaedics",
    "clinic_or_affiliation": "Ortho Clinic, Vijay Nagar",
    "hospital_id": "H011",
    "experience_years": 7,
    "consultation_duration": 25,
    "available_now": false,
    "queue_count": 3,
    "max_daily_patients": 18,
    "workload": 25.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.3
  },
  {
    "doctor_id": "D072",
    "name": "Dr. Asha Agrawal",
    "qualification": "MBBS, DA (Anaesthesia)",
    "specialty": "Anaesthesiology",
    "clinic_or_affiliation": "Regency Hospital, Sarvodaya Nagar",
    "hospital_id": "H004",
    "experience_years": 10,
    "consultation_duration": 30,
    "available_now": true,
    "queue_count": 6,
    "max_daily_patients": 24,
    "workload": 32.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.3
  },
  {
    "doctor_id": "D073",
    "name": "Dr. Anshuman Agrawal",
    "qualification": "MBBS, DNB, MNAMS (Ophthalmics)",
    "specialty": "Ophthalmology",
    "clinic_or_affiliation": "Eye Care Centre, The Mall",
    "hospital_id": "H013",
    "experience_years": 13,
    "consultation_duration": 15,
    "available_now": true,
    "queue_count": 0,
    "max_daily_patients": 30,
    "workload": 39.0,
    "emergency_available": false,
    "teleconsultation_available": false,
    "rating": 3.8
  },
  {
    "doctor_id": "D074",
    "name": "Dr. Titiksha Agrawal",
    "qualification": "MS (Ophthalmics)",
    "specialty": "Ophthalmology",
    "clinic_or_affiliation": "Eye Care Centre, The Mall",
    "hospital_id": "H014",
    "experience_years": 16,
    "consultation_duration": 20,
    "available_now": true,
    "queue_count": 3,
    "max_daily_patients": 36,
    "workload": 46.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 3.8
  },
  {
    "doctor_id": "D075",
    "name": "Dr. Ashish Agrawal",
    "qualification": "MBBS, MS (Ophthalmology)",
    "specialty": "Ophthalmology",
    "clinic_or_affiliation": "Regency Super Speciality Hospital",
    "hospital_id": "H004",
    "experience_years": 19,
    "consultation_duration": 25,
    "available_now": true,
    "queue_count": 6,
    "max_daily_patients": 42,
    "workload": 53.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 3.9
  },
  {
    "doctor_id": "D076",
    "name": "Dr. Shipra Agrawal",
    "qualification": "MBBS, MD (Anaesthesia)",
    "specialty": "Anaesthesiology",
    "clinic_or_affiliation": "Regency Hospital, Sarvodaya Nagar",
    "hospital_id": "H004",
    "experience_years": 22,
    "consultation_duration": 30,
    "available_now": false,
    "queue_count": 0,
    "max_daily_patients": 18,
    "workload": 60.0,
    "emergency_available": false,
    "teleconsultation_available": true,
    "rating": 3.9
  },
  {
    "doctor_id": "D077",
    "name": "Dr. Devi Prasad Agrawal",
    "qualification": "MBBS, MD (Medicine)",
    "specialty": "General Medicine",
    "clinic_or_affiliation": "Swaroop Nagar, Kanpur",
    "hospital_id": "H017",
    "experience_years": 25,
    "consultation_duration": 15,
    "available_now": true,
    "queue_count": 3,
    "max_daily_patients": 24,
    "workload": 67.0,
    "emergency_available": true,
    "teleconsultation_available": false,
    "rating": 4.0
  },
  {
    "doctor_id": "D078",
    "name": "Dr. Deepak Agrawal",
    "qualification": "MBBS, MS (Surgery)",
    "specialty": "General Surgery",
    "clinic_or_affiliation": "Swaroop Nagar, Kanpur",
    "hospital_id": "H018",
    "experience_years": 28,
    "consultation_duration": 20,
    "available_now": false,
    "queue_count": 6,
    "max_daily_patients": 30,
    "workload": 74.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.0
  },
  {
    "doctor_id": "D079",
    "name": "Dr. Gulab Chandra Agrawal",
    "qualification": "MBBS, FCGP",
    "specialty": "General Medicine",
    "clinic_or_affiliation": "Meston Road, Kanpur",
    "hospital_id": "H019",
    "experience_years": 5,
    "consultation_duration": 25,
    "available_now": true,
    "queue_count": 0,
    "max_daily_patients": 36,
    "workload": 81.0,
    "emergency_available": false,
    "teleconsultation_available": true,
    "rating": 4.1
  },
  {
    "doctor_id": "D080",
    "name": "Dr. Hari Ram Agrawal",
    "qualification": "MBBS, DMRE, FICRI (Radiodiagnosis)",
    "specialty": "Radiology",
    "clinic_or_affiliation": "New Leelamani Hospital, Civil Lines",
    "hospital_id": "H004",
    "experience_years": 8,
    "consultation_duration": 30,
    "available_now": true,
    "queue_count": 3,
    "max_daily_patients": 42,
    "workload": 88.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.1
  },
  {
    "doctor_id": "D081",
    "name": "Dr. Pawan Kumar Agrawal",
    "qualification": "MBBS, MD (Radiodiagnosis)",
    "specialty": "Radiology",
    "clinic_or_affiliation": "Benajhavar Road, Kanpur",
    "hospital_id": "H001",
    "experience_years": 11,
    "consultation_duration": 15,
    "available_now": true,
    "queue_count": 6,
    "max_daily_patients": 18,
    "workload": 25.0,
    "emergency_available": true,
    "teleconsultation_available": false,
    "rating": 4.2
  },
  {
    "doctor_id": "D082",
    "name": "Dr. Pooja Agrawal",
    "qualification": "MBBS, MD (Pharmacology)",
    "specialty": "Pharmacology",
    "clinic_or_affiliation": "GSVM Medical College",
    "hospital_id": "H002",
    "experience_years": 14,
    "consultation_duration": 20,
    "available_now": true,
    "queue_count": 0,
    "max_daily_patients": 24,
    "workload": 32.0,
    "emergency_available": false,
    "teleconsultation_available": true,
    "rating": 4.2
  },
  {
    "doctor_id": "D083",
    "name": "Dr. Pramod Kumar Agrawal",
    "qualification": "MBBS, M.S. (Surgery)",
    "specialty": "General Surgery",
    "clinic_or_affiliation": "Kulwanti Hospital, Kanpur",
    "hospital_id": "H008",
    "experience_years": 17,
    "consultation_duration": 25,
    "available_now": false,
    "queue_count": 3,
    "max_daily_patients": 30,
    "workload": 39.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.3
  },
  {
    "doctor_id": "D084",
    "name": "Dr. Neerja Agrawal",
    "qualification": "MBBS",
    "specialty": "General Medicine",
    "clinic_or_affiliation": "Darshanpurwa, Kanpur",
    "hospital_id": "H004",
    "experience_years": 20,
    "consultation_duration": 30,
    "available_now": true,
    "queue_count": 6,
    "max_daily_patients": 36,
    "workload": 46.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.3
  },
  {
    "doctor_id": "D085",
    "name": "Dr. Ratan Agrawal",
    "qualification": "MBBS, MS (Surgery)",
    "specialty": "General Surgery",
    "clinic_or_affiliation": "S.R. Hospital, Kidwai Nagar",
    "hospital_id": "H005",
    "experience_years": 23,
    "consultation_duration": 15,
    "available_now": false,
    "queue_count": 0,
    "max_daily_patients": 42,
    "workload": 53.0,
    "emergency_available": false,
    "teleconsultation_available": false,
    "rating": 3.8
  },
  {
    "doctor_id": "D086",
    "name": "Dr. Rohit Agrawal",
    "qualification": "MBBS, MD (Paediatrics)",
    "specialty": "Paediatrics",
    "clinic_or_affiliation": "Lakshya Hospital, Kidwai Nagar",
    "hospital_id": "H016",
    "experience_years": 26,
    "consultation_duration": 20,
    "available_now": true,
    "queue_count": 3,
    "max_daily_patients": 18,
    "workload": 60.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 3.8
  },
  {
    "doctor_id": "D087",
    "name": "Dr. Tripti Agrawal",
    "qualification": "MBBS, MS (Obst. & Gyne.)",
    "specialty": "Obstetrics & Gynaecology",
    "clinic_or_affiliation": "Agrawal Clinic, Shivaji Nagar",
    "hospital_id": "H007",
    "experience_years": 29,
    "consultation_duration": 25,
    "available_now": true,
    "queue_count": 6,
    "max_daily_patients": 24,
    "workload": 67.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 3.9
  },
  {
    "doctor_id": "D088",
    "name": "Dr. Sunil Kumar Agrawal",
    "qualification": "MBBS, MD (Paediatrics)",
    "specialty": "Paediatrics",
    "clinic_or_affiliation": "Kanpur",
    "hospital_id": "H008",
    "experience_years": 6,
    "consultation_duration": 30,
    "available_now": true,
    "queue_count": 0,
    "max_daily_patients": 30,
    "workload": 74.0,
    "emergency_available": false,
    "teleconsultation_available": true,
    "rating": 3.9
  },
  {
    "doctor_id": "D089",
    "name": "Dr. Sunita Agrawal",
    "qualification": "MBBS, DGO",
    "specialty": "Obstetrics & Gynaecology",
    "clinic_or_affiliation": "Sarvodaya Nagar, Kanpur",
    "hospital_id": "H009",
    "experience_years": 9,
    "consultation_duration": 15,
    "available_now": true,
    "queue_count": 3,
    "max_daily_patients": 36,
    "workload": 81.0,
    "emergency_available": true,
    "teleconsultation_available": false,
    "rating": 4.0
  },
  {
    "doctor_id": "D090",
    "name": "Dr. Vaibhav Agrawal",
    "qualification": "MBBS, MD (Path.)",
    "specialty": "Pathology",
    "clinic_or_affiliation": "Regency Hospital, Sarvodaya Nagar",
    "hospital_id": "H004",
    "experience_years": 12,
    "consultation_duration": 20,
    "available_now": false,
    "queue_count": 6,
    "max_daily_patients": 42,
    "workload": 88.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.0
  },
  {
    "doctor_id": "D091",
    "name": "Dr. Roshni Agrawal",
    "qualification": "MBBS, MD (Microbiology)",
    "specialty": "Microbiology",
    "clinic_or_affiliation": "Regency Hospital, Sarvodaya Nagar",
    "hospital_id": "H004",
    "experience_years": 15,
    "consultation_duration": 25,
    "available_now": true,
    "queue_count": 0,
    "max_daily_patients": 18,
    "workload": 25.0,
    "emergency_available": false,
    "teleconsultation_available": true,
    "rating": 4.1
  },
  {
    "doctor_id": "D092",
    "name": "Dr. Vineet Agrawal",
    "qualification": "MBBS, MD (Paediatrics)",
    "specialty": "Paediatrics",
    "clinic_or_affiliation": "Kanpur",
    "hospital_id": "H012",
    "experience_years": 18,
    "consultation_duration": 30,
    "available_now": false,
    "queue_count": 3,
    "max_daily_patients": 24,
    "workload": 32.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.1
  },
  {
    "doctor_id": "D093",
    "name": "Dr. Vishal Agrawal",
    "qualification": "MBBS, MS (Orthopaedics)",
    "specialty": "Orthopaedics",
    "clinic_or_affiliation": "Astha Clinic, The Mall",
    "hospital_id": "H013",
    "experience_years": 21,
    "consultation_duration": 15,
    "available_now": true,
    "queue_count": 6,
    "max_daily_patients": 30,
    "workload": 39.0,
    "emergency_available": true,
    "teleconsultation_available": false,
    "rating": 4.2
  },
  {
    "doctor_id": "D094",
    "name": "Dr. Iqbal Ahmad",
    "qualification": "MBBS, MD (Medicine)",
    "specialty": "General Medicine",
    "clinic_or_affiliation": "Kanpur",
    "hospital_id": "H014",
    "experience_years": 24,
    "consultation_duration": 20,
    "available_now": true,
    "queue_count": 0,
    "max_daily_patients": 36,
    "workload": 46.0,
    "emergency_available": false,
    "teleconsultation_available": true,
    "rating": 4.2
  },
  {
    "doctor_id": "D095",
    "name": "Dr. Ishtiaque Ahmad",
    "qualification": "MBBS, DCH",
    "specialty": "Paediatrics",
    "clinic_or_affiliation": "Bindki, Fatehpur",
    "hospital_id": "H015",
    "experience_years": 27,
    "consultation_duration": 25,
    "available_now": true,
    "queue_count": 3,
    "max_daily_patients": 42,
    "workload": 53.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.3
  },
  {
    "doctor_id": "D096",
    "name": "Dr. Jamal Uddin Ahmad",
    "qualification": "MBBS",
    "specialty": "General Medicine",
    "clinic_or_affiliation": "Apollo Hospital, Chunniganj, Kanpur",
    "hospital_id": "H005",
    "experience_years": 30,
    "consultation_duration": 30,
    "available_now": true,
    "queue_count": 6,
    "max_daily_patients": 18,
    "workload": 60.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 4.3
  },
  {
    "doctor_id": "D097",
    "name": "Dr. Jamil Ahmad",
    "qualification": "MBBS, MS (Surgery)",
    "specialty": "General Surgery",
    "clinic_or_affiliation": "Mahsa Hospital & Mohammadia Hospital",
    "hospital_id": "H017",
    "experience_years": 7,
    "consultation_duration": 15,
    "available_now": false,
    "queue_count": 0,
    "max_daily_patients": 24,
    "workload": 67.0,
    "emergency_available": false,
    "teleconsultation_available": false,
    "rating": 3.8
  },
  {
    "doctor_id": "D098",
    "name": "Dr. Faujia Jamil",
    "qualification": "MBBS, DGO (Obst. & Gyne.)",
    "specialty": "Obstetrics & Gynaecology",
    "clinic_or_affiliation": "UFWC Humanyu Bagh, Kanpur",
    "hospital_id": "H018",
    "experience_years": 10,
    "consultation_duration": 20,
    "available_now": true,
    "queue_count": 3,
    "max_daily_patients": 30,
    "workload": 74.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 3.8
  },
  {
    "doctor_id": "D099",
    "name": "Dr. Mohd. Ahmad",
    "qualification": "MBBS, MD, DM (Cardiology)",
    "specialty": "Cardiology",
    "clinic_or_affiliation": "Institute of Cardiology, Kanpur",
    "hospital_id": "H001",
    "experience_years": 13,
    "consultation_duration": 25,
    "available_now": false,
    "queue_count": 6,
    "max_daily_patients": 36,
    "workload": 81.0,
    "emergency_available": true,
    "teleconsultation_available": true,
    "rating": 3.9
  },
  {
    "doctor_id": "D100",
    "name": "Dr. Rana Ahmad",
    "qualification": "MBBS, MS, DGO (Obst. & Gyne.)",
    "specialty": "Obstetrics & Gynaecology",
    "clinic_or_affiliation": "Faize-am Charitable Hospital, Parade",
    "hospital_id": "H020",
    "experience_years": 16,
    "consultation_duration": 30,
    "available_now": true,
    "queue_count": 0,
    "max_daily_patients": 42,
    "workload": 88.0,
    "emergency_available": false,
    "teleconsultation_available": true,
    "rating": 3.9
  }
];
export const INITIAL_APPOINTMENTS = [
  {
    "appointment_id": "A001",
    "patient_name": "Patient A001",
    "doctor_id": "D001",
    "hospital_id": "H001",
    "appointment_time": "2026-08-14 09:00",
    "priority": "MEDIUM",
    "estimated_duration": 15,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A002",
    "patient_name": "Patient A002",
    "doctor_id": "D002",
    "hospital_id": "H002",
    "appointment_time": "2026-08-14 09:10",
    "priority": "LOW",
    "estimated_duration": 20,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A003",
    "patient_name": "Patient A003",
    "doctor_id": "D003",
    "hospital_id": "H003",
    "appointment_time": "2026-08-14 09:20",
    "priority": "LOW",
    "estimated_duration": 25,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A004",
    "patient_name": "Patient A004",
    "doctor_id": "D004",
    "hospital_id": "H004",
    "appointment_time": "2026-08-14 09:30",
    "priority": "LOW",
    "estimated_duration": 30,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A005",
    "patient_name": "Patient A005",
    "doctor_id": "D005",
    "hospital_id": "H002",
    "appointment_time": "2026-08-14 09:40",
    "priority": "LOW",
    "estimated_duration": 15,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A006",
    "patient_name": "Patient A006",
    "doctor_id": "D006",
    "hospital_id": "H006",
    "appointment_time": "2026-08-14 09:50",
    "priority": "HIGH",
    "estimated_duration": 20,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A007",
    "patient_name": "Patient A007",
    "doctor_id": "D007",
    "hospital_id": "H002",
    "appointment_time": "2026-08-14 10:00",
    "priority": "LOW",
    "estimated_duration": 25,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A008",
    "patient_name": "Patient A008",
    "doctor_id": "D008",
    "hospital_id": "H008",
    "appointment_time": "2026-08-14 10:10",
    "priority": "LOW",
    "estimated_duration": 30,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A009",
    "patient_name": "Patient A009",
    "doctor_id": "D009",
    "hospital_id": "H009",
    "appointment_time": "2026-08-14 10:20",
    "priority": "LOW",
    "estimated_duration": 15,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A010",
    "patient_name": "Patient A010",
    "doctor_id": "D010",
    "hospital_id": "H010",
    "appointment_time": "2026-08-14 10:30",
    "priority": "LOW",
    "estimated_duration": 20,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A011",
    "patient_name": "Patient A011",
    "doctor_id": "D011",
    "hospital_id": "H011",
    "appointment_time": "2026-08-14 10:40",
    "priority": "HIGH",
    "estimated_duration": 25,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A012",
    "patient_name": "Patient A012",
    "doctor_id": "D012",
    "hospital_id": "H012",
    "appointment_time": "2026-08-14 10:50",
    "priority": "LOW",
    "estimated_duration": 30,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A013",
    "patient_name": "Patient A013",
    "doctor_id": "D013",
    "hospital_id": "H013",
    "appointment_time": "2026-08-14 11:00",
    "priority": "LOW",
    "estimated_duration": 15,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A014",
    "patient_name": "Patient A014",
    "doctor_id": "D014",
    "hospital_id": "H014",
    "appointment_time": "2026-08-14 11:10",
    "priority": "LOW",
    "estimated_duration": 20,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A015",
    "patient_name": "Patient A015",
    "doctor_id": "D015",
    "hospital_id": "H001",
    "appointment_time": "2026-08-14 11:20",
    "priority": "LOW",
    "estimated_duration": 25,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A016",
    "patient_name": "Patient A016",
    "doctor_id": "D016",
    "hospital_id": "H016",
    "appointment_time": "2026-08-14 11:30",
    "priority": "MEDIUM",
    "estimated_duration": 30,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A017",
    "patient_name": "Patient A017",
    "doctor_id": "D017",
    "hospital_id": "H008",
    "appointment_time": "2026-08-14 11:40",
    "priority": "LOW",
    "estimated_duration": 15,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A018",
    "patient_name": "Patient A018",
    "doctor_id": "D018",
    "hospital_id": "H018",
    "appointment_time": "2026-08-14 11:50",
    "priority": "LOW",
    "estimated_duration": 20,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A019",
    "patient_name": "Patient A019",
    "doctor_id": "D019",
    "hospital_id": "H019",
    "appointment_time": "2026-08-14 12:00",
    "priority": "LOW",
    "estimated_duration": 25,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A020",
    "patient_name": "Patient A020",
    "doctor_id": "D020",
    "hospital_id": "H020",
    "appointment_time": "2026-08-14 12:10",
    "priority": "LOW",
    "estimated_duration": 30,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A021",
    "patient_name": "Patient A021",
    "doctor_id": "D021",
    "hospital_id": "H001",
    "appointment_time": "2026-08-14 12:20",
    "priority": "HIGH",
    "estimated_duration": 15,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A022",
    "patient_name": "Patient A022",
    "doctor_id": "D022",
    "hospital_id": "H004",
    "appointment_time": "2026-08-14 12:30",
    "priority": "LOW",
    "estimated_duration": 20,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A023",
    "patient_name": "Patient A023",
    "doctor_id": "D023",
    "hospital_id": "H003",
    "appointment_time": "2026-08-14 12:40",
    "priority": "LOW",
    "estimated_duration": 25,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A024",
    "patient_name": "Patient A024",
    "doctor_id": "D024",
    "hospital_id": "H004",
    "appointment_time": "2026-08-14 12:50",
    "priority": "LOW",
    "estimated_duration": 30,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A025",
    "patient_name": "Patient A025",
    "doctor_id": "D025",
    "hospital_id": "H005",
    "appointment_time": "2026-08-14 13:00",
    "priority": "LOW",
    "estimated_duration": 15,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A026",
    "patient_name": "Patient A026",
    "doctor_id": "D026",
    "hospital_id": "H006",
    "appointment_time": "2026-08-14 13:10",
    "priority": "HIGH",
    "estimated_duration": 20,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A027",
    "patient_name": "Patient A027",
    "doctor_id": "D027",
    "hospital_id": "H007",
    "appointment_time": "2026-08-14 13:20",
    "priority": "LOW",
    "estimated_duration": 25,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A028",
    "patient_name": "Patient A028",
    "doctor_id": "D028",
    "hospital_id": "H008",
    "appointment_time": "2026-08-14 13:30",
    "priority": "LOW",
    "estimated_duration": 30,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A029",
    "patient_name": "Patient A029",
    "doctor_id": "D029",
    "hospital_id": "H009",
    "appointment_time": "2026-08-14 13:40",
    "priority": "LOW",
    "estimated_duration": 15,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  },
  {
    "appointment_id": "A030",
    "patient_name": "Patient A030",
    "doctor_id": "D030",
    "hospital_id": "H010",
    "appointment_time": "2026-08-14 13:50",
    "priority": "LOW",
    "estimated_duration": 20,
    "status": "BOOKED",
    "notes": "Initial seeded appointment."
  }
];
